"""summaries

Revision ID: 9e3b6dbede16
Revises: e37567543ca7
Create Date: 2026-01-17 20:55:27.833331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e3b6dbede16'
down_revision: Union[str, Sequence[str], None] = 'e37567543ca7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('average_sleep', sa.Float(), nullable=False),
    sa.Column('total_spend', sa.Integer(), nullable=False),
    sa.Column('danger_tasks', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'period_start', 'period_end', name='uq_summary')
    )
    op.create_index(op.f('ix_summaries_user_id'), 'summaries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_summaries_user_id'), table_name='summaries')
    op.drop_table('summaries')
    # ### end Alembic commands ###
